### ISSUE TITLE
Schema Design Models 

### ISSUE THREAD

**Issue by 2fresh4stress** [Seminar-TextTalk/GroupProject#1]
List the properties our code will be using and give a description of each

**Comment by codepathreview** [comment]
Looks like you did not implement the following user story/ies:

* Wireframe images
* Updated group info in the Course Portal: Group Name + App Description.

Completed user stories checked-off in README.
We encourage everyone to complete all the required user stories for each assignment to demonstrate topic understanding. While we won't be regrading this submission anymore, we hope you try to complete all required user stories indicated here or on the Course Portal assignment tab for future assignments. 
/cc @codepathreview

**Comment by codepathreview** [comment]
Looks like you did not implement the following user story/ies:

 * GitHub Milestones created 

Completed user stories checked-off in README. We encourage everyone to complete all the required user stories for each assignment to demonstrate topic understanding. While we won't be regrading this submission anymore, we hope you try to complete all required user stories indicated here or on the Course Portal assignment tab for future assignments. 
/cc @codepathreview

**Comment by codepathreview** [comment]
Looks like you did not implement the following user story/ies:

 * Updated status of issues in Project board.
 * Sprint planned for next week (Issues created, assigned & added to project board).
 * Completed user stories checked-off in README
 * Gifs created to show build progress and added to README

Completed user stories checked-off in README. We encourage everyone to complete all the required user stories for each assignment to demonstrate topic understanding. While we won't be regrading this submission anymore, we hope you try to complete all required user stories indicated here or on the Course Portal assignment tab for future assignments. 
/cc @codepathreview

**Comment by 2fresh4stress** [comment]
Good morning,

We did create a wireframe. Instead of sketching it we did the bonus
activity and created a digital wireframe on figma and put the link in the
read me

**Comment by 2fresh4stress** [comment]
Is a Milestone and a issue diffrent? I put the objective, the due date, and
who is working on it in my issues.
